[package]
name = "dfwasm-test-runner"
description = "A test runner for dfwasm"
build = "build/build.rs"

repository.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
keywords.workspace = true

[dependencies]
dfwasm-compiler = { version = "0.1.0", path = "../dfwasm-compiler" }
dfwasm-template = { version = "0.1.0", path = "../dfwasm-template", features = [
    "codeclient",
] }
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0.98"
glob = "0.3.2"
wat = "1.229.0"
wasmi = "0.44.0"
