[package]
name = "dfwasm"
description = "Main CLI for the dfwasm compiler"
repository.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
default-run = "dfwasm"

[dependencies]
dfwasm-compiler = { version = "0.1.0", path = "../dfwasm-compiler" }
dfwasm-template = { version = "0.1.0", path = "../dfwasm-template", features = [
    "codeclient",
] }
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
clap = { version = "4.5.37", features = ["derive"] }
wat = "1.229.0"
