[package]
name = "dfwasm"
repository.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
dfwasm-compiler = { path = "../dfwasm-compiler" }
dfwasm-template = { path = "../dfwasm-template", features = ["codeclient"] }
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
clap = { version = "4.5.37", features = ["derive"] }
