[package]
name = "dfwasm-compiler"
description = "The dfwasm compiler"
repository.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
keywords.workspace = true

[dependencies]
wasmparser = "0.228.0"
dfwasm-template = { version = "0.1.0", path = "../dfwasm-template" }
thiserror = "2.0.12"
